# Generated by Django 3.2.8 on 2021-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
