# Generated by Django 3.2.8 on 2021-10-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dado_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='serie',
            field=models.CharField(max_length=20),
        ),
    ]
