# Generated by Django 3.2.8 on 2021-11-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dado_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='cpf',
            field=models.IntegerField(default=1458754),
            preserve_default=False,
        ),
    ]
