# Generated by Django 3.2.8 on 2021-11-04 22:22

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dado_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
    ]
