# Generated by Django 3.2.8 on 2021-11-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211112_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='serie',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
